### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SoluMilken** [Yoctol/ADEM#8]
- [ ] context, model_response, reference_response can have different dim of vector representation in `adem_with_encoder.py`
- [ ] add configs (yml) : model config, train config
- [ ] add user guide
- [ ] show model parameters before build graph
- [ ] provide preprocessing for text data ?
- [ ] add tensorflow unit test for flow control
